#pragma once

#include <iostream>
#include <fstream>
#include <string>
#include <exception>
#include <vector>
#include <math.h>
#include <sstream>
#include <assert.h>
#include <map>
#include <algorithm>
#include "algo.h"


typedef unsigned int u_int;
#define PREVIOUS_DAYS		200
#define STOCK_DATA_FILE						"../Data/Stock/fis_05.csv"
#define STOCK_DATA_FILE_WITH_INDICATORS		"../Data/Stock/fis_indicators.csv"
#define STOCK_DATA_FILE_TRAIN				"../Data/Stock/fis_indicators_train.csv"
#define STOCK_DATA_FILE_TEST				"../Data/Stock/fis_indicators_test.csv"
#define	SKIP_FIRST_ROW		1
#define COL_DIFF_SMA_EMA	6


#define DATE_INDEX							0
#define OPEN_INDEX							1
#define HIGH_INDEX							2
#define LOW_INDEX							3
#define CLOSE_INDEX							4
#define VOL_INDEX							5

#define TCP_MINUS_PCP_INDEX					6
#define PCP_INDEX							7
#define PHP_INDEX							8
#define PLP_INDEX							9
#define POP_INDEX							10

#define FIVE_DAY_SMA_CLOSING_INDEX			11
#define SIX_DAY_SMA_CLOSING_INDEX			12
#define TEN_DAY_SMA_CLOSING_INDEX			13
#define TWENTY_DAY_SMA_CLOSING_INDEX		14
#define FIFTY_DAY_SMA_CLOSING_INDEX			15
#define TWO_H_DAY_SMA_CLOSING_INDEX			16

#define FIVE_DAY_EMA_CLOSING_INDEX			17
#define SIX_DAY_EMA_CLOSING_INDEX			18
#define TEN_DAY_EMA_CLOSING_INDEX			19
#define TWENTY_DAY_EMA_CLOSING_INDEX		20
#define FIFTY_DAY_EMA_CLOSING_INDEX			21
#define TWO_H_DAY_EMA_CLOSING_INDEX			22

#define FIVE_DAY_TMA_CLOSING_INDEX			23
#define SIX_DAY_TMA_CLOSING_INDEX			24
#define TEN_DAY_TMA_CLOSING_INDEX			25
#define TWENTY_DAY_TMA_CLOSING_INDEX		26
#define FIFTY_DAY_TMA_CLOSING_INDEX			27
#define TWO_H_DAY_TMA_CLOSING_INDEX			28

#define ADL_CLOSING_INDEX					29
#define MACD_CLOSING_INDEX					30

#define FIVE_DAY_ACC_CLOSING_INDEX			31
#define SIX_DAY_ACC_CLOSING_INDEX			32
#define TEN_DAY_ACC_CLOSING_INDEX			33
#define TWENTY_DAY_ACC_CLOSING_INDEX		34
#define FIFTY_DAY_ACC_CLOSING_INDEX			35
#define FTWO_H_DAY_ACC_CLOSING_INDEX		36

#define FIVE_DAY_MOM_CLOSING_INDEX			37
#define SIX_DAY_MOM_CLOSING_INDEX			38
#define TEN_DAY_MOM_CLOSING_INDEX			39
#define TWENTY_DAY_MOM_CLOSING_INDEX		40
#define FIFTY_DAY_MOM_CLOSING_INDEX			41
#define TWO_H_DAY_MOM_CLOSING_INDEX			42

#define CHAIKIN_VOLATILITY_INDEX			43

#define FAST_STOCHASTIC_PERCENTK			44
#define FAST_STOCHASTIC_PERCENTD			45
#define SLOW_STOCHASTIC_PERCENTK			46
#define SLOW_STOCHASTIC_PERCENTD			47

#define WILLIAMS_PERCENT_R_INDEX			48
#define RELATIVE_STRENGTH_INDEX				49
#define BOLLINGER_MIDDLE_BAND_INDEX			50
#define BOLLINGER_HIGHER_BAND_INDEX			51
#define BOLLINGER_LOWER_BAND_INDEX			52

#define FIVED_HIGHEST_HIGH_INDEX			53
#define SIXD_HIGHEST_HIGH_INDEX				54
#define TEND_HIGHEST_HIGH_INDEX				55
#define TWENTYD_HIGHEST_HIGH_INDEX			56
#define FIFTYD_HIGHEST_HIGH_INDEX			57
#define TWO_HD_HIGHEST_HIGH_INDEX			58

#define FIVED_LOWEST_LOW_INDEX				59
#define SIXD_LOWEST_LOW_INDEX				60
#define TEND_LOWEST_LOW_INDEX				61
#define TWENTYD_LOWEST_LOW_INDEX			62
#define FIFTYD_LOWEST_LOW_INDEX				63
#define TWO_HD_LOWEST_LOW_INDEX				64

#define FIVED_MEDIAN_PRICE_INDEX			65
#define SIXD_MEDIAN_PRICE_INDEX				66
#define TEND_MEDIAN_PRICE_INDEX				67
#define TWENTYD_MEDIAN_PRICE_INDEX			68
#define FIFTYD_MEDIAN_PRICE_INDEX			69
#define TWO_HD_MEDIAN_PRICE_INDEX			70



